// Curated list of the most common breeds registered by pet owners in Chile —
// not the full FCI/CFA registry (300-400+ entries), which would make the
// picker unusable. "Mestizo" and an "Otra" escape hatch (handled by
// BreedPickerModal) cover everything not listed here.
export const DOG_BREEDS = [
  'Akita Americano',
  'Akita Inu',
  'Alaskan Malamute',
  'American Bully',
  'Basenji',
  'Basset Hound',
  'Beagle',
  'Bearded Collie',
  'Bernés de la Montaña',
  'Bichón Frisé',
  'Bichón Habanero',
  'Bloodhound',
  'Border Collie',
  'Border Terrier',
  'Boston Terrier',
  'Boxer',
  'Braco Alemán',
  'Bull Terrier',
  'Bull Terrier Miniatura',
  'Bulldog Francés',
  'Bulldog Inglés',
  'Cairn Terrier',
  'Cane Corso',
  'Cavalier King Charles Spaniel',
  'Chihuahua',
  'Chow Chow',
  'Cocker Spaniel',
  'Collie',
  'Coton de Tulear',
  'Dachshund (Salchicha)',
  'Dálmata',
  'Doberman',
  'Dogo Argentino',
  'Dogo de Burdeos',
  'English Springer Spaniel',
  'Fila Brasileiro',
  'Fox Terrier',
  'Galgo Español',
  'Golden Retriever',
  'Gran Danés',
  'Groenendael',
  'Husky Siberiano',
  'Jack Russell Terrier',
  'Kelpie Australiano',
  'Labrador Retriever',
  'Lhasa Apso',
  'Maltés',
  'Mastín Napolitano',
  'Mestizo',
  'Papillon',
  'Pastor Alemán',
  'Pastor Australiano',
  'Pastor Belga',
  'Pekinés',
  'Perro de Agua Español',
  'Pinscher Miniatura',
  'Pit Bull Terrier',
  'Podenco Ibicenco',
  'Pointer',
  'Pomerania',
  'Poodle (Caniche)',
  'Pug',
  'Rottweiler',
  'Samoyedo',
  'San Bernardo',
  'Schnauzer',
  'Setter Irlandés',
  'Shar Pei',
  'Shiba Inu',
  'Shih Tzu',
  'Spitz Alemán',
  'Staffordshire Bull Terrier',
  'Terranova',
  'Vizsla',
  'Weimaraner',
  'West Highland White Terrier',
  'Whippet',
  'Yorkshire Terrier',
].sort((a, b) => a.localeCompare(b, 'es'));

export const CAT_BREEDS = [
  'Abisinio',
  'American Curl',
  'American Shorthair',
  'Angora Turco',
  'Azul Ruso',
  'Bengalí',
  'Birmano',
  'Bombay',
  'Bosque de Noruega',
  'British Longhair',
  'British Shorthair',
  'Burmés',
  'Chartreux',
  'Cornish Rex',
  'Cymric',
  'Devon Rex',
  'Doméstico de Pelo Corto (Mestizo)',
  'Doméstico de Pelo Largo (Mestizo)',
  'Egipcio Mau',
  'Exótico de Pelo Corto',
  'Himalayo',
  'Javanés',
  'Khao Manee',
  'Korat',
  'Kurilian Bobtail',
  'LaPerm',
  'Maine Coon',
  'Manx',
  'Munchkin',
  'Nebelung',
  'Ocicat',
  'Oriental de Pelo Corto',
  'Persa',
  'Peterbald',
  'Ragamuffin',
  'Ragdoll',
  'Savannah',
  'Scottish Fold',
  'Selkirk Rex',
  'Siamés',
  'Siberiano',
  'Singapura',
  'Snowshoe',
  'Sokoke',
  'Somalí',
  'Sphynx (Esfinge)',
  'Tonkinés',
  'Toyger',
  'Van Turco',
  'York Chocolate',
].sort((a, b) => a.localeCompare(b, 'es'));
