export const COLLECTIONS = {
  USERS: 'users',
  PETS: 'pets',
  VETERINARIANS: 'veterinarians',
  STORES: 'stores',
  PRODUCTS: 'products',
  APPOINTMENTS: 'appointments',
  MATCHES: 'matches',
  CHATS: 'chats',
  LOST_PETS: 'lostPets',
  ORDERS: 'orders',
  MEDICAL_VISITS: 'medicalVisits',
  WALKERS: 'walkers',
  GROOMERS: 'groomers',
  REVIEWS: 'reviews',
  TRAINERS: 'trainers',
  REMINDERS: 'reminders',
  VET_INVITES: 'vetInvites',
  LITTERS: 'litters',
  REPORTS: 'reports',
  BLOCKS: 'blocks',
  CLIENT_LINKS: 'clientLinks',
  PLACES: 'places',
  PLACE_REVIEWS: 'placeReviews',
  EVENTS: 'events',
  POS_SALES: 'posSales',
} as const;

export const RTDB_PATHS = {
  MESSAGES: 'messages',
  PRESENCE: 'presence',
  CHAT_MEMBERS: 'chatMembers',
  NOTIFICATIONS: 'notifications',
} as const;
